spring.application.name=gateway-service

# cloud server configuration
# we are telling user-service to communicate config server and fetch it & use it
#spring.config.import=optional:configserver:http://localhost:8888

spring.config.import=optional:configserver:https://akshay-fitness-configservers.onrender.com

spring.cloud.config.fail-fast=true
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.max-attempts=6
spring.cloud.config.retry.multiplier=1.5
spring.cloud.config.retry.max-interval=10000