spring.application.name=aiservice
server.port = 8082

#spring.data.mongodb.uri=mongodb://localhost/aiactivityfitness
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=airecommendationfitness

# this is used to register with eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Configuration for Apache Kafka i.e how to connect & communicate with kafka
# data will be sent in key-value pair
# activity: <ACTIVITY> (activity object)
# this mapping is needed because the data which we are sending should also store on Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=activity-processor-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# don't use type headers
# the activity object sent over the network in kafka, it is consumed and it's type will set i.e Activity object
# package com.fitness.activityservice.model; it is a type header i.e type of Activity, it will pass in header
# and we dont need that header because here we will create our own object of Activity
# so this header will not be used that's why we makes it false
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# here we have to mention the class type because the data will come, it comes in the form of object
# and we have to deserialize the object in AiService
# but in which class it will map?(or the created object will map to which class?) so we have to mention the class type
# so whenever the data comes to kafka i.e Activity Object, this will map to the Activity class
spring.kafka.consumer.properties.spring.json.value.default.type=com.fitness.aiservice.model.Activity

# it means that all the packages are trusted so give access them
spring.kafka.consumer.properties.spring.json.trusted.packages="*"

#this is not a setting but we are mentioning the topic name of kafka
kafka.topic.name=activity-events

# i have used environment variable here and url, key will be injected by environment variable
# steps to go Environment variable
# click AiserviceApplication at top where we run the project
# edit configuration and give GEMINI_URL and GEMINI_KEY
gemini.api.url = ${GEMINI_URL}
gemini.api.key = ${GEMINI_KEY}