#
#server.port=8082
#
##spring.data.mongodb.uri=mongodb://localhost/aiactivityfitness
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=aiactivityfitness
#
## this is used to register with eureka
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#
## Force Eureka to use IP instead of Windows hostname
#eureka.instance.prefer-ip-address=true
#eureka.instance.hostname=localhost
#
## Configuration for Apache Kafka i.e how to connect & communicate with kafka
## data will be sent in key-value pair
## activity: <ACTIVITY> (activity object)
## this mapping is needed because the data which we are sending should also store on Kafka
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#user.service.url=http://localhost:8081
#
##this is not a setting but we are mentioning the topic name of kafka
#kafka.topic.name=activity-events



server.port=${PORT:8082}

#  #? %23 (its URL-encoded form) in the password, and /aiactivityfitness moved to right after .mongodb.net, before the ?.
#The # character has special meaning in URIs (it starts a "fragment" ? everything after it gets cut off and ignored).
# Since your password contains two literal # characters, MongoDB will only ever see PHW as the password, not the real thing ? this would fail to connect.
# spring.data.mongodb.uri=mongodb+srv://aiactivityfitness:PHW#84#jeor@aifitnesstracker.o4syp7s.mongodb.net/?appName=AIFitnessTracker/aiactivityfitness
spring.data.mongodb.uri=mongodb+srv://aiactivityfitness:PHW%2384%23jeor@aifitnesstracker.o4syp7s.mongodb.net/aiactivityfitness?appName=AIFitnessTracker

eureka.client.service-url.defaultZone=https://akshay-fitness-eureka.onrender.com/eureka/

spring.kafka.bootstrap-servers=kafka-121817-akshay121817-2a34.k.aivencloud.com:25221
spring.kafka.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="avnadmin" password="${KAFKA_PASSWORD}";
spring.kafka.ssl.trust-store-location=classpath:aiven-ca.pem
spring.kafka.ssl.trust-store-type=PEM

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

user.service.url=https://akshay-fitness-userservice.onrender.com
kafka.topic.name=activity-events