
server.port=8082

#spring.data.mongodb.uri=mongodb://localhost/aiactivityfitness
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=aiactivityfitness

# this is used to register with eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Configuration for Apache Kafka i.e how to connect & communicate with kafka
# data will be sent in key-value pair
# activity: <ACTIVITY> (activity object)
# this mapping is needed because the data which we are sending should also store on Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#this is not a setting but we are mentioning the topic name of kafka
kafka.topic.name=activity-events