#
#server.port = 8083
#
##spring.data.mongodb.uri=mongodb://localhost/aiactivityfitness
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=airecommendationfitness
#
## this is used to register with eureka
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#
## IMPORTANT: force IP-based registration
## Before adding these lines, Eureka was telling Gateway: that ?AI-Service is running on LAPTOP-SSPH6LG9.mshome.net?
## But Gateway said: ?I don?t understand this laptop name. I can?t find it.?
## So Gateway failed ? 500 error
## By adding these two lines
## This tells Eureka: ?When someone asks where my service is, give my IP address, not my laptop name.?
## So instead of: LAPTOP-SSPH6LG9.mshome.net Eureka gives: 127.0.0.1
## hostname=localhost : This tells Eureka: ?If you need a name, just use localhost.?
## and localhost is a name every computer understands.
## Why this works in simple words
## -> Laptop names are not always readable
## -> IP address (127.0.0.1) is always readable
## -> localhost is always safe
## You told Eureka to use safe and simple addresses.
#eureka.instance.prefer-ip-address=true
#eureka.instance.hostname=localhost
#
#
## Configuration for Apache Kafka i.e how to connect & communicate with kafka
## data will be sent in key-value pair
## activity: <ACTIVITY> (activity object)
## this mapping is needed because the data which we are sending should also store on Kafka
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.consumer.group-id=activity-processor-group
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
#
## don't use type headers
## the activity object sent over the network in kafka, it is consumed and it's type will set i.e Activity object
## package com.fitness.activityservice.model; it is a type header i.e type of Activity, it will pass in header
## and we dont need that header because here we will create our own object of Activity
## so this header will not be used that's why we makes it false
#spring.kafka.consumer.properties.spring.json.use.type.headers=false
#
## here we have to mention the class type because the data will come, it comes in the form of object
## and we have to deserialize the object in AiService
## but in which class it will map?(or the created object will map to which class?) so we have to mention the class type
## so whenever the data comes to kafka i.e Activity Object, this will map to the Activity class
#spring.kafka.consumer.properties.spring.json.value.default.type=com.fitness.aiservice.model.Activity
#
## it means that all the packages are trusted so give access them
#spring.kafka.consumer.properties.spring.json.trusted.packages="*"
#
##this is not a setting but we are mentioning the topic name of kafka
#kafka.topic.name=activity-events
#
## i have used environment variable here and url, key will be injected by environment variable
## steps to go Environment variable
## click AiserviceApplication at top where we run the project
## edit configuration and give GEMINI_URL and GEMINI_KEY
#gemini.api.url = ${GEMINI_URL}
#gemini.api.key = ${GEMINI_KEY}






server.port=${PORT:8083}

spring.data.mongodb.uri=mongodb+srv://aiactivityfitness:PHW%2384%23jeor@aifitnesstracker.o4syp7s.mongodb.net/airecommendationfitness?appName=AIFitnessTracker

eureka.client.service-url.defaultZone=https://akshay-fitness-eureka.onrender.com/eureka/

spring.kafka.bootstrap-servers=kafka-121817-akshay121817-2a34.k.aivencloud.com:25221
spring.kafka.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="avnadmin" password="${KAFKA_PASSWORD}";
spring.kafka.ssl.trust-store-location=file:/app/aiven-ca.pem
spring.kafka.ssl.trust-store-type=PEM

spring.kafka.consumer.group-id=activity-processor-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.fitness.aiservice.model.Activity
spring.kafka.consumer.properties.spring.json.trusted.packages="*"

kafka.topic.name=activity-events
gemini.api.url=${GEMINI_URL}
gemini.api.key=${GEMINI_KEY}