eureka.client.service-url.defaultZone=http://localhost:8761/eureka

server.port=8080

# Gateway is a service or an entry point for external wall to send request in your application
# If an external wall want to access APIs so he send request to Gateway
# and gateway routes the request to the correct service by routing configurations

# This gives a name to the route: user-service.
spring.cloud.gateway.routes[0].id=user-service

# This tells the gateway to forward requests to the service registered as USER-SERVICE in Eureka using load balancing (lb://).
# lb means load balances, it is necessary to work and Using load balancer with Eureka service ID
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
# any request comes to this path (Path=/api/users/**)  so it will redirect to lb://USER-SERVICE

#This route will match any request that starts with /api/v1/users/ and send it to USER-SERVICE.
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/users/**
#spring.cloud.gateway.routes[0].filters[0]=StripPrefix=2


spring.cloud.gateway.routes[1].id=activity-service
spring.cloud.gateway.routes[1].uri=lb://ACTIVITY-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/activities/**

spring.cloud.gateway.routes[2].id=product-service
spring.cloud.gateway.routes[2].uri=lb://AI-SERVICE
<<<<<<< HEAD
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/recommendations/**

spring.security.oauth2.resourceserver.jwt.jwk-set-url=http://localhost:8181/realms/fitness-app/protocol/openid-connect/certs

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/fitness-app
=======
<<<<<<< HEAD
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/recommendations/**
=======
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/recommendations/**

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8181/realms/fitness-app/protocol/openid-connect/certs
>>>>>>> 0f03ffb (complete backend commit)
>>>>>>> 65e5e6f04cb6da8729f16b8c153f642faadfb8c3
