spring.application.name=eureka

# Server port
server.port=8761

# Disable client registration since this is the server
# Eureka is a service registry in which other services are registered
# it is like an attendance system
# we don't want eureka server register himself so that's why we write "register-with-eureka"
# which means eurka will not register himself in eureka
eureka.client.register-with-eureka = false
eureka.client.fetch-registry = false


# for inter service communication we need rest clients