spring.application.name=configserver
server.port=8888

## firstly we have to dictate the profile
spring.profiles.active=native
## here we are telling to the config server to search all the config in this location
spring.cloud.config.native.search-location=classpath:/config